name: Create Archive
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Archive Package
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: 'BareBones红石显示.mcpack'
        exclusions: '*.git* /*node_modules/* .editorconfig /Images/* LICENSE *.md'
        type: 'zip'
        
    - uses: actions/upload-artifact@v3
      with:
        name: BareBones红石显示
        path: ./BareBones红石显示.mcpack
