name: Create Archive
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'BareBones红石显示.mcpack'
        exclusions: '*.git* /*node_modules/* .editorconfig Images/ LICENSE *.md '
        type: 'zip'
    - uses: actions/upload-artifact@v2
      with:
        name: Archive Prerelease
        path: ./BareBones红石显示.mcpack
