name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: TheDoctor0/zip-release@0.4.1
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        type: 'zip'
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./release.zip
